# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('deficit-round-robin-example', ['deficit-round-robin'])
    obj.source = 'deficit-round-robin-example.cc'

