# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('base-class', ['core'])
    module.source = [
        'model/base-class.cc',
        'helper/base-class-helper.cc',
        'model/destination-ipadress.cc',
        'model/destination-mask.cc',
        'model/destination-portnumber.cc',
        'model/protoco-number.cc',
        'model/source-ipaddress.cc',
        'model/source-mask.cc',
        'model/source-portnumber.cc',
        'model/traffic-class.cc',
        'model/filter.cc',
        ]

    module_test = bld.create_ns3_module_test_library('base-class')
    module_test.source = [
        'test/base-class-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'base-class'
    headers.source = [
        'model/base-class.h',
        'helper/base-class-helper.h',
        'model/destination-ipadress.h',
        'model/filter-element.h',
        'model/destination-mask.h',
        'model/destination-portnumber.h',
        'model/protoco-number.h',
        'model/source-ipaddress.h',
        'model/source-mask.h',
        'model/source-portnumber.h',
        'model/traffic-class.h',
        'model/filter.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

